sudo: required

language: bash

dist: xenial

services:
  - docker

script:
  - TAG="debian-zcash_1.0.13"
  - CONT_NAME="zcash-node"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker build -t cultclassik/$CONT_NAME .
  - docker images
  - docker tag cultclassik/$CONT_NAME cultclassik/$CONT_NAME:latest
  - docker tag cultclassik/$CONT_NAME cultclassik/$CONT_NAME:$TAG
  - docker push cultclassik/$CONT_NAME:$TAG
  - docker push cultclassik/$CONT_NAME
